### ISSUE TITLE
Does not handle App.Foo = App.Bar = Ember.Route.extend

### ISSUE THREAD

**Issue by fivetanley** [fivetanley/ember-cli-migrator#16]
currently rewrites as `var App.Foo = var App.Bar = Ember.Route.extend`

**Comment by tonysherbondy** [comment]
Hey @fivetanley, I noted this as well as a couple other things in todos. I could probably find some time to take care of them before Ember Conf if you think they would help for your training session. The todos were the following:
* Analyst.FindPageMixin = Em.Mixin.create(Analyst.PageMixin, {
* helpers
* use new visitor syntax
* App.Something = App.SomethingElse = Ember.Object.extend();

The new visitor syntax one is probably the most potentially disrupting.

**Comment by tonysherbondy** [comment]
Fixed in #46

**Comment by tonysherbondy** [comment]
Oops, didn't mean to close your issue. Feel free to close if you agree.
