### ISSUE TITLE
Preserve Comments:

### ISSUE THREAD

**Issue by kiwiupover** [fivetanley/ember-cli-migrator#24]
Right now the a comment is preserved inside a global function but removes any comments before and after the global function. 

```js
// This comment is removed
/* global moment */ will be removed too
App.DavesComponent = Ember.Component.extend({
   
   // this comment is retained
   somethingCool: function(){
   }.on('didInsertElement')

})
// Also this comment is removed
```

If you point me in the right direction I try and write a fix. 

Cheers

**Comment by kiwiupover** [comment]
@tonysherbondy What will take to preserve the comments. I will take a shot at writing the code if you point me in the right direction. 

Cheers
Dave

**Comment by fivetanley** [comment]
@kiwiupover I noticed this happening as well. Perhaps I could trouble @benjamn one more time with some recast advice to not have comment nodes removed. We are typically using `this.remove()` in the Visitor API (which I know is deprecated, we should switch soon).

**Comment by tonysherbondy** [comment]
@kiwiupover @fivetanley I think this has to do with the way I split files. I think I can fix it pretty quickly. Let me take a look.

**Comment by kiwiupover** [comment]
Thanks this will be very helpful.

Cheers
