### ISSUE TITLE
Stability of the tool

### ISSUE THREAD

**Issue by mikepmunroe** [fivetanley/ember-cli-migrator#32]
Related to emberjs/website#1994

I haven't used this migrator yet, but it came up during our initial documentation meeting. What are your feelings on the stability of the tool and maintenance of it going forward? We may document its use within new Ember docs as a tool for migrating to Ember-CLI.

**Comment by fivetanley** [comment]
Stability and maintenance feels good. @igorT @tonysherbondy and I are working on it. We're preparing a training around Ember CLI around it and using it in client projects. Finding lots of edge cases but working through them and happy to put time into it if others are willing to test/use.

**Comment by mikepmunroe** [comment]
OK, that is great news. We will probably come back around at some point with questions, but sounds like it is actively being worked on and will continue so.
