### ISSUE TITLE
error installing 

### ISSUE THREAD

**Issue by koryteg** [fivetanley/ember-cli-migrator#43]
I get these errors while installing:

`Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo`

but I am running as sudo.

**Comment by koryteg** [comment]
I needed to open xcode and agree to the terms... that was dumb.

but now I am getting this error: 
In file included from ../src/ffi.cc:2:
../src/ffi.h:57:43: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> FFIPrepCif(const Arguments& args);
                                          ^~~~~~~~~
                                          v8::internal::Arguments

**Comment by fivetanley** [comment]
Hmm, one of my dependencies is likely depending on something with a C extension that needs an update for 0.12/iojs. I'll look into it ASAP

**Comment by fivetanley** [comment]
I think this has been fixed in 0.5.0. Can you try installing with `npm install -g ember-cli-migrator@0.5.x` for me?

**Comment by koryteg** [comment]
it works now thanks!!
