### ISSUE TITLE
support ember-tools / commonJS style exports

### ISSUE THREAD

**Issue by fivetanley** [fivetanley/ember-cli-migrator#51]

**Comment by rauhryan** [comment]
I'd love to help... you might now believe this, but I have no idea how to iterate on an npm package

Like stupidly, day 1 type things... how do I run the cli locally? its a -g install but how do i test the cli end to end

could you add that to the readme maybe?

**Comment by fivetanley** [comment]
Ah cool! Yeah I should've added these instructions a long time ago. Here they are https://github.com/fivetanley/ember-cli-migrator/blob/master/README.md#running-the-cli-locally
